### ISSUE TITLE
File empty 

### ISSUE THREAD

**Issue by RRebo** [rpianezza/GenomeDelta#1] opened 2024-09-25 18:25 UTC
Hello,
Thank you for this cool tool. I was trying to use it with some of my data but I got this error:
```
SyntaxError: invalid syntax
Error: The requested file (/home/data/rrebollo/drosophila/genomeDelta/goth101ONdmsj23-GD-credibility.bed) could not be opened. Error message: (No such file or directory). Exiting!
The file /home/data/rrebollo/drosophila/genomeDelta/goth101ONdmsj23-GD.fasta is empty. GenomeDelta was not able to identify any new region in FASTA file. Check if you prepared everything according to the Manual. Try to change the parameters to reduce stringency
```
Does this mean that I simply have no "absent" insertions in my fastq file compared to the assembly? If so, I would like to try the tool to understand the outputs. Would you have any sample data you could make it available on the github? As an example dataset?
Thank you,
Rita

**Comment by rpianezza** [comment] 2024-09-26 06:14
Hi Rita,

thanks for trying my tool. Indeed, it looks like you don't have any coverage gap in your data, at least not bigger than 1000 bp (the default threshold, which you can modify by specifying "--_min_len xxx_" in the call).

To understand the tool and the intermediate files you can go to the walkthrough [here](https://github.com/rpianezza/GenomeDelta/tree/main/walkthrough), where you have some sample data which should result in one repetitive candidate.

Keep me updated!

Best,
Riccardo

**Comment by RRebo** [comment] 2024-09-26 06:22
That's perfect, thanks!
Rita

**Comment by RRebo** [comment] 2024-09-26 07:54
Hi Riccardo, I'm sorry, but I can't make it work. Here is what I'm doing so you can check if I'm messing something up. I installed with conda but I'm using the command `bash ../linux/main.sh` command because I can't call GenomeDelta directly. I decided to run everything from the walkthrough directory `bash ../linux/main.sh --fq test-reads.fq --fa test-assembly.fasta --of . --prefix test --t 10` but it gives me this error:

```
rm: cannot remove './test-GD.fasta-e': No such file or directory
[E::fai_build_core] File truncated at line 1
[faidx] Could not build fai index ./test-GD-non_rep.fasta.fai

-- Column specification ------------------------------------------------------------
cols(
  cluster = col_double(),
  credibility = col_double(),
  n = col_double()
)

Error: './test-GD-non_rep.fasta.fai' does not exist in current working directory ('/home/data/rrebollo/GenomeDelta/walkthrough').
Execution halted
(GenomeDelta) rrebollo@bf2i-galaxy:/home/data/rrebollo/GenomeDelta/walkthrough$ bash ../linux/main.sh --fq test-reads.fq --fa test-assembly.fasta --of . --prefix test --t 10^C

```

These are all the files I see: 
![image](https://github.com/user-attachments/assets/589e060f-53bb-42ab-b1f2-47f6482e9a39)

You can see that I'm actually working in a PC, with a MobaxTerm interface connected to my lab cluster, but I don't think it should change anything...

Anyway, if you can help me figure out what I'm doing wrong, it would be lovely. Thanks,
Rita

**Comment by rpianezza** [comment] 2024-09-26 09:28
I reproduced your command and I did get the same output as you. So you are not doing anything wrong, but rather I realised there is something wrong with the walkthrough files, I will fix that asap.

Anyhow, the only step which didn't work is the visualisation. Everything else it's in your folder. The important files to look at are:

test-GD.fasta --> contains all of the found coverage gaps (you should have 25, in this case)
test-GD-candidates.fasta --> contains the consensus sequences generated from the clustered gaps (in this case you will find only 1, as planned. The name of the cluster contains the mean credibility score and the number of sequences in the cluster)
test-GD.bed --> the genomic coordinates of the gaps

I will work now to fix the Walkthrough. Thanks again.

Riccardo

**Comment by RRebo** [comment] 2024-09-26 10:45
Thanks! Keep me informed and I'll try again.
Rita

**Comment by rpianezza** [comment] 2024-09-26 11:53
Now it should be fixed. I uploaded a new [test-assembly.fasta](https://github.com/rpianezza/GenomeDelta/blob/main/walkthrough/test-assembly.fasta) which works.
Riccardo

**Closed as completed** 2024-09-30 11:45 UTC
